### ISSUE TITLE
Issues Compiling 

### ISSUE THREAD

**Issue by rp4k** [sibvic/MQ4Inject#1]
When trying to compile i am getting the following error. 

`\MQ4Inject.csproj(1,1): error MSB4025: The project file could not be loaded. Data at the root level is invalid. Line 1, position 1.`

**Comment by rp4k** [comment]
i fixed the error, but now when i try to add the source file it doesn't inject properly all of the different snippets

**Comment by sibvic** [comment]
It looks like you specify the parameters incorrectly
